### ISSUE TITLE
Wrong depth order of PortalEntity

### ISSUE THREAD

**Issue by WeAthFoLD** [evshiron/IngressCraft#1]
I noticed that the rendering of portal entity sometimes have a wrong order. Entities that should be rendered after it are not correctly covered. In the PortalRenderer.java I see that you've closed the depth mask, maybe opening that will solve the issue?

Anyways, minecraft has 2 render stages (opaque and transparent), you can use the following code in entity to make it render in transparent stage:

``` java
@Override
public boolean shouldRenderInPass(int pass) {
    return pass == 1; //0:opaque 1:transparent
}
```

Where the rendering is much more free. You can close the depth mask and alpha test without causing too much trouble.

**Comment by evshiron** [comment]
Sounds reasonable. Will take a look at it.
